name: Reload PythonAnywhere Webapp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Wait for auto-pull to settle
        run: sleep 15
      
      - name: Reload PythonAnywhere Webapp
        uses: jensvog/pythonanywhere-webapp-reload-action@v1
        with:
          host: 'www.pythonanywhere.com'
          username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          api-token: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
          domain-name: assistantofkc.pythonanywhere.com
